Dbranch
karina-klinkeviciute/rainbow-challenge-front pull request #72
Opened 2021-12-13 11:45 UTC by don4t4s

2021-12-13 20:25 UTC, ignasbagdonas commented on .gradle/buildOutputCleanup/cache.properties
> +gradle.version=6.8
.gradle folderio nereikia į source control traukti, jis automatiškai susikuria pas kiekvieną iš mūsų kompuose. Please, išimk. :)

2021-12-13 20:26 UTC, ignasbagdonas requested changes
Išimti .gradle folderį.

2021-12-13 20:40 UTC, ralekna commented on lib/utils/model/reg_model.dart
> +  //String is_lgbtqia;
When I leave such commented out code I leave an expiration note that would tell for how long and why to keep such code. Otherwise just delete and forget :)

2021-12-13 20:43 UTC, karina-klinkeviciute commented on lib/utils/model/reg_model.dart
> +  //String is_lgbtqia;
those will be needed after I fix the backend. Here everything is alright - they haven't been removed but prepared in advance

2021-12-13 21:28 UTC, karina-klinkeviciute commented on lib/pages/registration/fields/email.dart
> +        return "This is not a valid email";
are localizations for this and other strings added?

2021-12-14 07:40 UTC, don4t4s commented on .gradle/buildOutputCleanup/cache.properties
> +gradle.version=6.8
Ok, išiimtas...

2021-12-14 12:57 UTC, merged